# 基础镜像 python 3.7
FROM python:3.7
LABEL maintainer="merlinzhu@lexin.com" version="0.0.1"

# 设置时区
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' >/etc/timezone

WORKDIR /home/quarkml
COPY quarkml-0.0.1-py3-none-any.whl /home/quarkml/
COPY entrypoint.sh /home/
COPY server.py /home/
# jupyterlab 是交互使用端， flask 是服务请求端， quarkml 是执行引擎
RUN pip config set global.trusted-host pypi.tuna.tsinghua.edu.cn && \
    pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && \
    pip install --upgrade pip setuptools && \
    pip install jupyterlab && \
    pip install flask && \
    pip install quarkml-0.0.1-py3-none-any.whl && rm -rf /root/.cache/pip/

RUN rm -rf quarkml-0.0.1-py3-none-any.whl

ENTRYPOINT ["/home/entrypoint.sh"]